version: '3.8'

services:
  inventario-service:
    build: ./inventario-service
    container_name: inventario-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_INVENTARIO}
      - APP_INVENTARIO_SERVICE_URL=http://inventario-service:8080/api/inventario

  usuario-service:
    build: ./usuario-service
    container_name: usuario-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_USUARIO}

  ventas-service:
    build: ./ventas-service
    container_name: ventas-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_VENTAS}

  arriendo-service:
    build: ./arriendo-service
    container_name: arriendo-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_ARRIENDO}
      - APP_INVENTARIO_SERVICE_URL=http://inventario-service:8080/api/inventario

  carrito-service:
    build: ./carrito-service
    container_name: carrito-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_CARRITO}
      - APP_INVENTARIO_SERVICE_URL=http://inventario-service:8080/api/inventario

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - inventario-service
      - carrito-service